Document: plymouth-theme-equilibrium
Title: Debian plymouth-theme-equilibrium Manual
Author: <insert document author here>
Abstract: This manual describes what plymouth-theme-equilibrium is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/plymouth-theme-equilibrium/plymouth-theme-equilibrium.sgml.gz

Format: postscript
Files: /usr/share/doc/plymouth-theme-equilibrium/plymouth-theme-equilibrium.ps.gz

Format: text
Files: /usr/share/doc/plymouth-theme-equilibrium/plymouth-theme-equilibrium.text.gz

Format: HTML
Index: /usr/share/doc/plymouth-theme-equilibrium/html/index.html
Files: /usr/share/doc/plymouth-theme-equilibrium/html/*.html
